[[datasets]]

[[datasets.subsets]]
caption_dropout_rate = 0.01
caption_tag_dropout_rate = 0.25
caption_extension = ".txt"
image_dir = "/workspace/final_reversed"
num_repeats = 1
shuffle_caption = true


[general]
resolution = 1024
enable_bucket = true
min_bucket_reso = 256
bucket_no_upscale = true
max_bucket_reso = 4096
bucket_reso_steps = 64
